# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: tg-mock
    main: ./cmd/tg-mock
    binary: tg-mock
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # Phase 2: Uncomment these after Linux is verified
      # - windows
      # - darwin
    goarch:
      - amd64
      - arm64
    # Phase 2: Uncomment to exclude Windows ARM64
    # ignore:
    #   - goos: windows
    #     goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: tg-mock-archive
    formats:
      - tar.gz
    # Phase 2: Uncomment for Windows .zip files
    # format_overrides:
    #   - goos: windows
    #     formats:
    #       - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: watzon
    name: tg-mock
  draft: false
  prerelease: auto
