// cmd/codegen/methods.go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

func generateMethods(spec *Spec, outDir string) error {
	f, err := os.Create(filepath.Join(outDir, "methods.go"))
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by codegen. DO NOT EDIT.")
	fmt.Fprintln(f, "package gen")
	fmt.Fprintln(f)

	// Generate FieldSpec type
	fmt.Fprintln(f, "// FieldSpec describes a method parameter")
	fmt.Fprintln(f, "type FieldSpec struct {")
	fmt.Fprintln(f, "\tName     string")
	fmt.Fprintln(f, "\tTypes    []string")
	fmt.Fprintln(f, "\tRequired bool")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)

	// Generate MethodSpec type
	fmt.Fprintln(f, "// MethodSpec describes a Bot API method")
	fmt.Fprintln(f, "type MethodSpec struct {")
	fmt.Fprintln(f, "\tName    string")
	fmt.Fprintln(f, "\tReturns []string")
	fmt.Fprintln(f, "\tFields  []FieldSpec")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)

	// Generate method registry
	fmt.Fprintln(f, "// Methods is the registry of all Bot API methods")
	fmt.Fprintln(f, "var Methods = map[string]MethodSpec{")

	names := make([]string, 0, len(spec.Methods))
	for name := range spec.Methods {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		m := spec.Methods[name]
		fmt.Fprintf(f, "\t%q: {\n", name)
		fmt.Fprintf(f, "\t\tName:    %q,\n", m.Name)
		fmt.Fprintf(f, "\t\tReturns: %#v,\n", m.Returns)

		if len(m.Fields) > 0 {
			fmt.Fprintln(f, "\t\tFields: []FieldSpec{")
			for _, field := range m.Fields {
				fmt.Fprintf(f, "\t\t\t{Name: %q, Types: %#v, Required: %v},\n",
					field.Name, field.Types, field.Required)
			}
			fmt.Fprintln(f, "\t\t},")
		}

		fmt.Fprintln(f, "\t},")
	}

	fmt.Fprintln(f, "}")

	return nil
}
